import { Injectable } from "@angular/core";
import { Observable, of } from "rxjs";

import { RegionData } from "../../region-data.to";

@Injectable({
    providedIn: "root"
})
export class StateDetailService {

    private readonly STATES = {
        BW: {
            name: "Baden-Württemberg",
            ags: "BW",
            state: "Baden-Württemberg",
            bez: "Land",
            gen: "Baden-Württemberg",    
            population: 11069533,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        BY: {
            name: "Bayern",
            ags: "BY",
            state: "Bayern",
            bez: "Land",
            gen: "Bayern",    
            population: 13076721,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        BE: {
            name: "Berlin",
            ags: "BW",
            state: "Berlin",
            bez: "Land",
            gen: "Berlin",    
            population: 3644826,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        BB: {
            name: "Brandenburg",
            ags: "BB",
            state: "Brandenburg",
            bez: "Land",
            gen: "Brandenburg",    
            population: 2511917,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        HB: {
            name: "Bremen",
            ags: "HB",
            state: "Bremen",
            bez: "Land",
            gen: "Bremen",    
            population: 682986,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        HH: {
            name: "Hamburg",
            ags: "HH",
            state: "Hamburg",
            bez: "Land",
            gen: "Hamburg",    
            population: 1841179,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        HE: {
            name: "Hessen",
            ags: "HE",
            state: "Hessen",
            bez: "Land",
            gen: "Hessen",    
            population: 6265809,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        MV: {
            name: "Mecklenburg-Vorpommern",
            ags: "MV",
            state: "Mecklenburg-Vorpommern",
            bez: "Land",
            gen: "Mecklenburg-Vorpommern",    
            population: 1609675,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        NI: {
            name: "Niedersachsen",
            ags: "NI",
            state: "Niedersachsen",
            bez: "Land",
            gen: "Niedersachsen",    
            population: 7982448,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        NW: {
            name: "Nordrhein-Westfalen",
            ags: "NW",
            state: "Nordrhein-Westfalen",
            bez: "Land",
            gen: "Nordrhein-Westfalen",    
            population: 17932651,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        RP: {
            name: "Rheinland-Pfalz",
            ags: "RP",
            state: "Rheinland-Pfalz",
            bez: "Land",
            gen: "Rheinland-Pfalz",    
            population: 4084844,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        SL: {
            name: "Saarland",
            ags: "SL",
            state: "Saarland",
            bez: "Land",
            gen: "Saarland",    
            population: 990509,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        ST: {
            name: "Sachsen-Anhalt",
            ags: "ST",
            state: "Sachsen-Anhalt",
            bez: "Land",
            gen: "Sachsen-Anhalt",    
            population: 2208321,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        SN: {
            name: "Sachsen",
            ags: "SN",
            state: "Sachsen",
            bez: "Land",
            gen: "Sachsen",    
            population: 4077937,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        },
        SH: {
            name: "Schleswig-Holstein",
            ags: "SH",
            state: "Schleswig-Holstein",
            bez: "Land",
            gen: "Schleswig-Holstein",    
            population: 2896712,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        }, 
        TH: {
            name: "Thüringen",
            ags: "TH",
            state: "Thüringen",
            bez: "Land",
            gen: "Thüringen",    
            population: 2134393,
            population_density_km: 0,
            population_male: 0,
            population_female: 0,  
        }
    }

    constructor() { }

    public getStateDetail(stateCode: string): Observable<RegionData> {
        return of(this.STATES[stateCode]);
    }

}